### ISSUE TITLE
Lost connection

### ISSUE THREAD

**Issue by foempe** [Fockaert/rika-firenet-custom-component#28]
Hi,
i have no connection anymore.
can sombody please help me?

Logger: homeassistant.config_entries
Bron: config_entries.py:749
Eerst voorgekomen: 24 juni 2025 om 18:57:41 (4 gebeurtenissen)
Laatst gelogd: 15:15:05

Error setting up entry xxxxxx for rika_firenet
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rika_firenet/__init__.py", line 60, in async_setup_entry
    await hass.config_entries.async_forward_entry_setup(entry, platform)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by nyckosleducmanage** [comment]
Hello,

I have exactly the same error after upgrade HA from 2025.4.3 to 2025.7.3

Thanks

**Comment by poldi871** [comment]
I had the same problem after the following updates:
- Core to: 2025.7.4
- OS to: 16.0

Cause:
In "__init__.py", the call to "async_forward_entry_setup()" is obsolete, as already noted elsewhere.

Solution (Thanks to ChatGPT)

Replace (see: here manually commented lines at about line 57 ff.):

```
 #    for platform in PLATFORMS:
 #        if entry.options.get(platform, True):
 #            coordinator.platforms.append(platform)
 #            await hass.config_entries.async_forward_entry_setup(entry, platform)
```

with:

```
   coordinator.platforms.extend(
        [platform for platform in PLATFORMS if entry.options.get(platform, True)]
    )

    await hass.config_entries.async_forward_entry_setups(entry, coordinator.platforms)
```

I haven't fully tested the change yet, but the Rika module is starting up again and at least my self-implemented start commands for the oven work.
I hope this helps someone and can be implemented by the author.

**Comment by davidfischer-ch** [comment]
Great, I also need it. Hopefully we are in Summer but Winter is Coming :)

**Comment by davidfischer-ch** [comment]
The solution from @poldi871 works properly. But I cannot confirm if the call to `async_forward_entry_setups` is legit.

**Comment by Fockaert** [comment]
Merged PR #31 please check whether this is fixed

**Comment by poldi871** [comment]
I just updated from the git repository. It works for me. Thanks!!

**Comment by poldi871** [comment]
Now I've discovered a problem (again). The power slider no longer works. For details, see [#26](https://github.com/Fockaert/rika-firenet-custom-component/issues/26).
